### ISSUE TITLE
Explore tcell as a termbox alternative

### ISSUE THREAD

**Issue by mum4k** [mum4k/termdash#100]
https://github.com/gdamore/tcell

We should add a new API wrapper like the one for termbox:
https://github.com/mum4k/termdash/tree/master/terminal/termbox

And document how users can choose termbox or tcell when initialising.

**Comment by mum4k** [comment]
What is left is to solve the problem of color differences between termbox and tcell. We could approach this by adding a new color mode that will translate colors the same way termbox does. More details in the comment history of #224.

@kvnxiao, thank you for your help with #224, please let me know if you are also planning to work on the color differences, or if you would prefer I help with that.

**Comment by kvnxiao** [comment]
I assume the colour differences would be a simple translation mapping between the specific colours that termbox uses. I will probably have time to update the wiki, but if it is alright with you I am hoping to ask you to help with the colour differences (I'm in my last semester of undergrad and things are ramping up for me).

**Comment by mum4k** [comment]
Sounds good @kvnxiao, I will look at the color differences. Thank you very much for you help thus far and best of luck with your studies.

**Comment by kvnxiao** [comment]
I've added a new wiki page here https://github.com/mum4k/termdash/wiki/Tcell-API but it's currently unlinked and not in the sidebar as the changes have not been released yet.
