### ISSUE TITLE
Titles on grid rows

### ISSUE THREAD

**Issue by slok** [mum4k/termdash#181]
Hi! 

Thanks for implementing this awesome library with a well-designed API.

I'm using the grid layout style but I'm missing how to add titles to the rows, I only can add titles to the widgets, and vice-versa (using containers directly I can have titles in rows but not titles on widgets).

Is this possible and I'm missing something?

Thank you!

**Comment by mum4k** [comment]
Hi @slok,

thank you very much for the feedback. Your observation is correct, the current implementation of the grid API doesn't allow users to specify options for the intermediate containers.

The good news is that this was fairly easy to add. I have pushed #182 into the devel branch.

I would appreciate if you could try building from the devel branch and let me know if this works as expected.

Jakub

**Comment by slok** [comment]
Wow! that was fast!

I just tested and works like a charm! thanks! :)

![](https://i.imgur.com/YJNAq2q.png)

**Comment by mum4k** [comment]
Thanks a lot for confirming, much appreciated.
