### ISSUE TITLE
Allow "no value" on lineChart

### ISSUE THREAD

**Issue by slok** [mum4k/termdash#184]
Hi!

Would be nice to allow no values on the linechart, at this moment the linechart only supports float64 values (that defaults to `0` if no value) but sometimes you don't have values to render on the graph. A  `0` and a `nil` are two different things and could make the graph *break* by the Y axis getting very big (from 0 to N) in very high value graphs without very differences.

An example to show the graph when we don't have values:

We have this graph on Prometheus that shows us that from 5:27 to 5:29 doesn't have values (not rendered and the Y axis doesn't show `0`):

![](https://i.imgur.com/01n5TWj.png)

Same as above but rendered using termdash:

![](https://i.imgur.com/qyfskDa.png)

The problem with the termdash rendering is that the "no values" are rendered with the default float64 as `0` and the Y axis shows `0` making the scale of the graph bigger and by this harder to get insights from it.

The first approach to solve this that comes to my mind is by having `*float64` as value unit or similar (custom type with pointers on no values) in another method like `SeriesWithNils`, `SeriesWithNoValues` so it doesn't break the current API.

**Comment by mum4k** [comment]
Thank you @slok, this certainly is an interesting use case that I didn't think about.

Luckily when it comes to the API, we might have another option that results in a compatible change. The float type can also have a special value [NaN](https://godoc.org/math#NaN), which literally means "not-a-number". So we can adjust the LineChart to skip values that are NaN.

To be able to prioritize this work, can you help me understand if this is a "nice-to-have" enhancement or something that you would require right away?

**Comment by slok** [comment]
Hi @mum4k!

As always thank you for responding so fast, first of all, I didn't know about the NaN! thanks!

At this moment I'm developing a new application in my spare time (is private for now, I'll make it public when I have the basic functionality, but I'm near), this application is a simplified [_grafana_](https://grafana.com) for terminal, so you can load dashboards based on config files and retrieve the metrics from different datasource, configure metric colors, thresholds, timerange...

Example:

![](https://i.imgur.com/dJZwMMI.png)

I've selected termdash as the rendering engine for the widgets, although it lacks some functionality compared to libraries like [termui](https://github.com/gizak/termui), the API is cleaner and I think it has better looking, so once again, congrats :)

In the case of priority, I would say that this is very important if you render high values that don't vary a lot, so in my opinion is a requirement, but doesn't need to be right away, although if it's not too complicated for a person that lacks the knowledge of the internals of the library, I could contribute with a PR.

**Comment by mum4k** [comment]
Thank you for sharing the screenshot @slok, that looks really good!

Understood about the priority. I would say the change itself will have medium complexity. It doesn't require knowledge of the infrastructure of termdash, and should be completely contained within the implementation of the [linechart](https://github.com/mum4k/termdash/blob/master/widgets/linechart). However it will need to be propagated throughout all the layers of the linechart's implementation. I would roughly outline the required changes as follows:

1. Code that determines the min,max values needs to do the right thing for NaNs (ignore them):
https://github.com/mum4k/termdash/blob/a9515f27215c8c7f3c0df731c4e86103cb9cdb9d/widgets/linechart/linechart.go#L54-L65
2. The internal [axes](https://github.com/mum4k/termdash/tree/master/widgets/linechart/internal/axes) package might need some changes to support the NaN values:
3. The logic that draws the values will need to know that it is supposed to skip over NaNs without attempting to draw the braille lines:
https://github.com/mum4k/termdash/blob/a9515f27215c8c7f3c0df731c4e86103cb9cdb9d/widgets/linechart/linechart.go#L408

I might be missing something, but that should be it in a nutshell. It is great to hear you might be willing to contribute a PR. I would suggest you look at the code in the linechart package and its surrounding libraries and see if you feel like sending the PR. Please let me know what you decide. If you prefer me doing this, considering this is important for you I can slot it in a week or two.

Also please don't hesitate to open issues for any of the missing features you mentioned. Happy to discuss further improvements we need to make. Or you could help by prioritizing any issues that already exist so we develop the right things.

**Comment by slok** [comment]
Thanks for the tips!

Checking your steps, hacking around a little bit  the code and making few changes I had good results, I need to check if I have corner cases, check the tests... but I'll do it with more calm in the following days and if everythings seems ok make the PR!

Before the changes:

![](https://i.imgur.com/DU6Ve8W.png)

After the changes:

![](https://i.imgur.com/EdxW4s5.png)

**Comment by mum4k** [comment]
Great news! Please feel free to ask me if you will have any questions.

**Comment by mum4k** [comment]
Fixed in the devel branch.
