### ISSUE TITLE
Question: How to modify border title once the widget is instantiated? 

### ISSUE THREAD

**Issue by miguelmota** [mum4k/termdash#221]
How to modify border title once the widget is instantiated?

**Comment by mum4k** [comment]
Hello @miguelmota, I am assuming you are asking about the container title? You should be able to utilize the [dynamic layout](https://github.com/mum4k/termdash/wiki/Dynamic-layout) feature.

In short you specify an ID for the container when creating it by passing this option:
https://github.com/mum4k/termdash/blob/68bf0566e6ec8effaf6e83400ef0046347a5f5f1/container/options.go#L308-L320

And then you can use the container.Update function, specifying the same ID and providing any set of new options, including a new title:
https://github.com/mum4k/termdash/blob/68bf0566e6ec8effaf6e83400ef0046347a5f5f1/container/container.go#L229-L235
However if you are asking about title of a specific widget, that might be different, please let me know.

**Comment by miguelmota** [comment]
@mum4k makes perfect sense; thanks!
