### ISSUE TITLE
Widget: Colored panel with text label

### ISSUE THREAD

**Issue by flaviostutz** [mum4k/termdash#239]
I wish I could create a panel with a colored background and a centered text.

Something like:
![image](https://user-images.githubusercontent.com/7790172/88596962-9a167680-d03c-11ea-8a8e-5cc5ce26a13c.png)

**Comment by flaviostutz** [comment]
In the example, the bar on the left of the square is a measurement bar that shows the CPU load percent.

**Comment by mum4k** [comment]
Hi @flaviostutz, did you try to achieve this behavior with the Gauge widget?

https://godoc.org/github.com/mum4k/termdash/widgets/gauge

The Gauge widget allows text alignment with these two options, so one can center the text:
https://godoc.org/github.com/mum4k/termdash/widgets/gauge#HorizontalTextAlign
https://godoc.org/github.com/mum4k/termdash/widgets/gauge#VerticalTextAlign

Additionally one can choose both the colors of the "filled" and the "empty" portions of the gauge:
https://godoc.org/github.com/mum4k/termdash/widgets/gauge#EmptyTextColor
https://godoc.org/github.com/mum4k/termdash/widgets/gauge#FilledTextColor

Can you try to see how far you can get with these? Once we identify the missing feature, we can add it of course.

**Comment by flaviostutz** [comment]
Great! I tried with Gauge using 100% as its value and it worked. In the meantime I was using Button with shadow black ;)

Thanks again!
