### ISSUE TITLE
Line chart uses blocks instead of lines

### ISSUE THREAD

**Issue by hi019** [mum4k/termdash#250]
Hi, I'm on Arch Linux and running [this](https://github.com/mum4k/termdash/blob/master/widgets/linechart/linechartdemo/linechartdemo.go) demo from GNOME Terminal. The Line chart font is not displaying correctly, is there a font I need to install? 
![demo](https://user-images.githubusercontent.com/65871571/98958995-db8a3f00-24d0-11eb-91ee-2a7880b0b637.png)

**Comment by mum4k** [comment]
Thank you for reaching out @hi019. This could be one of two things. It is either that the used font doesn't support unicode characters, or that the used terminal isn't compatible with `termbox-go`.

Can you try running the demo using `tcell` instead? The documentation for `tcell` is here:
https://github.com/mum4k/termdash/wiki/Tcell-API

An example of using `tcell` with `termdash` is here:
https://github.com/mum4k/termdash/blob/2a7dafa3a835dbe45d9a6eaa2f22e184666c8065/termdashdemo/termdashdemo.go#L489-L490

If this doesn't solve it, can you try it in a different terminal application and with a few different fonts to try to isolate the culprit?

**Comment by hi019** [comment]
Hi, sorry for my late reply. Since this is an issue on my end, I'm going to close this issue and update you if there is anything new. Thanks.

**Comment by mum4k** [comment]
Thank you @hi019, please don't hesitate to reach out if you will have any questions.
