### ISSUE TITLE
How to display the cursor position and color of textinput in Linux environment?

### ISSUE THREAD

**Issue by post707** [mum4k/termdash#318]
I use the formdemo
The execution results on Linux are as follows
<img width="380" alt="微信图片_20220118165527" src="https://user-images.githubusercontent.com/20917260/149903729-81de1956-1fed-45d4-81a1-239ba34ab7a8.png">

How to display the cursor position and color of textinput in Linux environment?
Thanks！

**Comment by mum4k** [comment]
Thank you for reaching out @post707. We have successfully used Termdash on Linux. To be noted, Termdash features heavily depend on the capabilities of the terminal emulator. To be able to utilize them correctly, we need to run in a terminal emulator supported by [tcell](https://github.com/gdamore/tcell).

XTerm and rxvt+ are examples of two terminal emulators that should work well.

**Comment by post707** [comment]
Thank you for your answer@mum4k .Is xshell or SecureCRT supported？

**Comment by post707** [comment]
I've solved it。Xhell is right by default。secretcrt需要勾选ANSI Color。

**Comment by mum4k** [comment]
Thank you for sharing the solution @post707.
