### ISSUE TITLE
Is there any way to render charts without handing over the entire terminal?

### ISSUE THREAD

**Issue by anderspitman** [mum4k/termdash#375]
I'm trying to add a few charts to my app, but still allow normal stdout/stderr logs to be shown. Is this possible?

**Comment by mum4k** [comment]
Hi @anderspitman that currently isn't supported. Termdash is a library built on top of terminal driver libraries (`tcell` and `termbox`). I believe both of those only work with exclusivbe access to the full terminal. At least that is what used to be true, I did not explore the latest changes and feature set of `tcell`.

If you are interested in exploring this further, we would first have to figure out if `tcell` supports running on a portion of a terminal and then make the necessary changes in Termdash to utilize such mode.

**Comment by anderspitman** [comment]
That makes sense. Thanks!
