### ISSUE TITLE
Add support for vertical text labels in the LineChart widget

### ISSUE THREAD

**Issue by mum4k** [mum4k/termdash#43]
The text can either have rotated characters, or just standard text characters flowing vertically.

This would be for the X axis, so that it can display longer custom labels.

**Comment by keithknott26** [comment]
This would be very helpful!

**Comment by mum4k** [comment]
This isn't too complicated, I think we can slot this for the next release. Stay tuned.

**Comment by mum4k** [comment]
This was pushed to the devel branch and will be in the next release.

Would be great if you could test it by building from devel and update this issue if anything goes wrong.
