### ISSUE TITLE
There is a potential race between Options() and Draw() calls

### ISSUE THREAD

**Issue by mum4k** [mum4k/termdash#63]
This affects widgets that calculate their minimum size based on what data they currently have.

The following causes a race:
1. infra calls Options()
1. user changes values in the widget
1. infra calls Draw(), potentially not respecting the min size.

**Comment by activeshadow** [comment]
Is this maybe the reason why a line chart with a min value > 0 still results in the Y Axis still being drawn all the way down to zero? I have a series that is in the range of 1600 - 1800, and my Y Axis is always from 0 to  max instead of min to max.

**Comment by mum4k** [comment]
That looks unrelated, this is a bug that would trigger an error when a terminal resize event happens at a particular time between getting the widget's options and drawing the widget.

What you are describing is actually a design choice I made, quite possibly because I didn't understand all the use cases. Would you mind filing a separate issue where we can discuss the use case? Once we are on the same page, we can add a new feature to the LineChart so that the Y axis isn't always zero based.

**Comment by mum4k** [comment]
@activeshadow fyi I had some time to test this and filed #92.
