### ISSUE TITLE
Support padding of containers

### ISSUE THREAD

**Issue by mum4k** [mum4k/termdash#72]
So widgets can have some space around themselves.

Probably a separate padding for top, bottom, left, right. These can be implemented as new container options:
https://github.com/mum4k/termdash/blob/master/container/options.go

The size of the padding should be supplied in relative terms, so that this behaves well with terminal resize. I.e. percentage of the containers width / height.

**Comment by infinytum** [comment]
I've started experimenting with this.

Currently implemented are 4 new options:
```go

// Adds 1 space of padding on the left
container.PaddingLeft(1)

// Adds 1 space of padding on the top
container.PaddingTop(1)

// Adds 1 space of padding on the right
container.PaddingRight(1)

// Adds 1 space of padding on the bottom
container.PaddingBottom(1)
```

On the testing part I might need some help. Currently not tested (Except for human testing)

Please see pull request #91 for code reviewing

**Comment by infinytum** [comment]
Alright, I added a test which tests all 4 padding methods

**Comment by infinytum** [comment]
I think a margin sounds good. Will look at the coding part asap.

**Comment by mum4k** [comment]
Thank you, I have filed #93 to track the margin feature. If you will be looking at that too, please send it in a separate PR.
