### ISSUE TITLE
Cleanup code issues on go report card

### ISSUE THREAD

**Issue by mum4k** [mum4k/termdash#83]
https://goreportcard.com/report/github.com/mum4k/termdash

Note: not all of the gocyclo issues should be cleaned up, some functions need to have those switch statements with many cases (like selecting a character). Similarly we don't really want to shorten tests. So the gocyclo category needs judgement.

The other categories are straightforward.

**Comment by infinytum** [comment]
I've created a pull-request #84 which fixes all except the go-cyclo errors
