### ISSUE TITLE
Support power shell on windows 10 and mintty using msys2

### ISSUE THREAD

**Issue by jcbritobr** [mum4k/termdash#99]
In power shell, on windows 10, the graphics get bad characters, and graphics becomes strange:
![image](https://user-images.githubusercontent.com/6579862/52098163-084bbb80-25b5-11e9-99ab-f664cf81a37a.png)

On msys2 mintty terminal, this library just dont works.

**Comment by mum4k** [comment]
Thank you for the bug report. I will try to spin this up on Windows and see what can be done.

**Comment by mum4k** [comment]
I have tried this today and have good and bad news.

First the good news - this seems to be working well in both the power shell and windows default console with minor tweaks. Looks like the default font both of these use doesn't support Unicode characters. But if you right-click on the top bar of the console window and choose properties, you can change the font. One of the pre-installed ones is "MS Gothic" which seems do handle Unicode well. I got this running in both the console and power shell.

Additional background:
https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line

The bad news is about mintty, indeed that doesn't work at all. Looks like termbox itself (what we use to render on a terminal) doesn't support mintty. I looked at alternatives and found tcell, which also claims to not support mintty with some explanation (see their README):

https://github.com/gdamore/tcell

If you can help me find a termbox / tcell alternative that does work on mintty I will be happy to make it work.

Please let me know if you managed to get this to work in power shell based on the instructions above.

**Comment by mum4k** [comment]
Also take a look at these fonts which might be better than the pre-installed one:

https://math.berkeley.edu/~serganov/ilyaz.org/software/fonts/

**Comment by mum4k** [comment]
Please feel free to let me know if you have further questions.

**Comment by mapl** [comment]
I want to throw in some cents that Microsoft is actually improving their console.
Interesting Blog

https://devblogs.microsoft.com/commandline/

Especially https://devblogs.microsoft.com/commandline/new-experimental-console-features/ show off some good progress in their preview windows 10 builds.

**Comment by mum4k** [comment]
That looks really promising, thanks @mapl. This gives us hope that termbox or tcell might be able to implement the support at some point.

**Comment by mapl** [comment]
There is coming up some neat stuff

BUILD 2019 Announcement Today

https://youtu.be/8gw0rXPMMPE

https://github.com/microsoft/terminal
